name: Run tests and linting

on:
  push:
    branches:
      - '*'

jobs:
  Run-tests-and-linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run lint
        run: yarn lint
      - name: Run tests
        run: CI=true yarn test
